POST http://localhost:8080/events
Content-Type: "application/json"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVrcmVtTmV3QGdtYWlsLmNvbSIsImV4cCI6MTcyNTMwNTg1MSwidXNlcklkIjo5fQ.muI3X4r053YwNhrEQzz6Nra3cUNCHXqzWtMvSqVIDtI

{
    "Name":"test 3",
    "Description":"Description 3",
    "Location":"Location 3"
}
